name: website

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  prerelease-docs-build-deploy:
    # IMPORTANT: this workflow also functions as a test for `docs-deploy-website-latest-release` in
    # releases.yml. Any fixes here should probably be duplicated there.
    permissions:
      contents: write
    if: github.repository_owner == 'jj-vcs' # Stops this job from running on forks
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # `.github/scripts/docs-build-deploy` will need to `git push` to the docs branch
          persist-credentials: true
      - run:  "git fetch origin gh-pages --depth=1"
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: 3.11
      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb
        with:
          version: "0.5.1"
      - name: Install dependencies, compile and deploy docs
        run: |
          git config user.name 'jj-docs[bot]'
          git config user.email 'jj-docs[bot]@users.noreply.github.io'
          export MKDOCS_SITE_NAME="Jujutsu docs (prerelease)"
          export MKDOCS_PRIMARY_COLOR="blue grey"
          .github/scripts/docs-build-deploy prerelease --push
      - name: "Show `git diff --stat`"
        run: git diff --stat gh-pages^ gh-pages || echo "(No diffs)"
